Server:
  Name: gin-admin-api
  Mode: dev
  Host: 0.0.0.0
  Port: 8081
  Pprof: false

Log:
  Mode: both
  Encoding: json

DBs:
  default:
    Host: 127.0.0.1
    Port: 3307
    User: root
    Pwd: 12345678
    Database: gin-admin
    # DataSource: root:12345678@tcp(127.0.0.1:3307)/gin-admin?charset=utf8mb4&parseTime=True&loc=PRC
    Pool:
      MaxConn: 10
      MaxIdle: 3

