Server:
  Name: gin-admin-api
  Mode: dev
  Host: 0.0.0.0
  Port: 9011
  Pprof: false

Log:
  Mode: both
  Encoding: plain
  Rotation: level-daily

DBs:
  default:
    Host: 127.0.0.1
    Port: 3307
    User: root
    Pwd: 123456
    Database: gin-admin
    # DataSource: root:123456@tcp(127.0.0.1:3307)/gin-admin?charset=utf8mb4&parseTime=True&loc=PRC
    Pool:
      MaxConn: 10
      MaxIdle: 3

