// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysAdmin = "sys_admin"

// SysAdmin mapped from table <sys_admin>
type SysAdmin struct {
	ID            int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID           string         `gorm:"column:uid;not null" json:"uid"`                                         // UID
	Realname      string         `gorm:"column:realname;not null" json:"realname"`                               // 真实姓名
	Mobile        string         `gorm:"column:mobile;not null" json:"mobile"`                                   // 电话号
	AreaCode      string         `gorm:"column:area_code;not null" json:"area_code"`                             // 区号
	Email         string         `gorm:"column:email;not null" json:"email"`                                     // EMAIL
	Weixin        string         `gorm:"column:weixin;not null" json:"weixin"`                                   // 微信号
	LastLoginTime time.Time      `gorm:"column:last_login_time" json:"last_login_time"`                          // 最后一次登录时间
	CreatedAt     time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 修改时间
	Operator      string         `gorm:"column:operator;not null" json:"operator"`                               // 操作人
	IsDeleted     bool           `gorm:"column:is_deleted;not null" json:"is_deleted"`                           // 是否删除
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                                    // 删除时间
}

// TableName SysAdmin's table name
func (*SysAdmin) TableName() string {
	return TableNameSysAdmin
}
